### PR TITLE
Update and fix docker-up.sh for Docker Compose v2

### LINKED ISSUE #65: Test A+ Docker scripts with Docker Compose v2 and fix them
A+ courses usually have the files docker-up.sh, docker-compose.yml and docker-compile.sh for local testing of the course and A+ in Docker containers. Docker Compose v2 was released in the autumn 2021 and it is not compatible with Compose v1. Test and fix the A+ Docker scripts so that they support the latest versions of Docker Compose and Docker Desktop for Mac (and Windows?).

UPDATE: the error message below seems to have been completely unrelated to the Docker Compose versions. If testing doesn't reveal any new issues, then newer Compose could work without changes in the A+ scripts.

From a teacher:

> This morning after updating docker desktop on a Windows I started to get the following error 

```
grader_1  | Internal Server Error: /default/aplus-json
grader_1  | Traceback (most recent call last):
grader_1  |   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 34, in inner
grader_1  |     response = get_response(request)
grader_1  |   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 115, in _get_response
grader_1  |     response = self.process_exception_by_middleware(e, request)
grader_1  |   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 113, in _get_response
grader_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
grader_1  |   File "/usr/local/lib/python3.9/dist-packages/aplus_auth/auth/django.py", line 61, in wrapper
grader_1  |     return func(request, *args, **kwargs)
grader_1  |   File "/srv/grader/util/auth.py", line 97, in wrapper
grader_1  |     return view_func(request, *args, course_key, **kwargs)
grader_1  |   File "/srv/grader/access/views.py", line 471, in aplus_json
grader_1  |     mf["children"] = children_recursion(m)
grader_1  |   File "/srv/grader/access/views.py", line 463, in children_recursion
grader_1  |     of["children"] = children_recursion(o)
grader_1  |   File "/srv/grader/access/views.py", line 456, in children_recursion
grader_1  |     _, exercise = config.exercise_entry(course["key"], str(of["key"]), '_root')
grader_1  |   File "/srv/grader/access/config.py", line 200, in exercise_entry
grader_1  |     exercise_root = self._exercise_root(course_root, exercise_key)
grader_1  |   File "/srv/grader/access/config.py", line 385, in _exercise_root
grader_1  |     data = self._process_exercise_data(course_root, data)
grader_1  |   File "/srv/grader/access/config.py", line 642, in _process_exercise_data
grader_1  |     default = recursion(data, default_lang, True)
grader_1  |   File "/srv/grader/access/config.py", line 633, in recursion
grader_1  |     v = self.TAG_PROCESSOR_DICT[tag](d, n, v, lang=lang)
grader_1  |   File "/srv/grader/access/config.py", line 102, in <lambda>
grader_1  |     'i18n': lambda root, parent, value, **kwargs: value.get(kwargs['lang']),
grader_1  | TypeError: unhashable type: 'list' 
```

I can't be sure now, but I think this error could be related to the Docker Compose changes.

### PR DESCRIPTION
**Pull request by ihalaij1**
Update the script so that it works better with Docker Compose v2.

Issues with Q and S commands not being captured on Windows WSL2 and macOS have also been fixed.

Fixes #65

### CODE REVIEW

**Review by PasiSa — APPROVED** [review]
Tested this on my WSL2 Windows, and seems to work.

File: docker-up.sh [hunk 1]
```diff
@@ -89,38 +90,38 @@ while [ "$1" ]; do
...
+            [ $? -eq 142 ] && { keep="x"; break; } # Timeout -> no second byte -> plain ESC
             ;;
     esac
 
-    # print status and help
+    # Print status and help
     echo
     echo "  List of alive containers:"
-    { docker container ls --filter "name=^${COMPOSE_PROJECT_NAME}_"  --format "{{.ID}}" | xargs docker container inspect --format '	{{.Name}}	{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}	{{range $p, $conf := .NetworkSettings.Ports}}{{$p}} {{end}}'; } 2>/dev/null || true
+    { docker container ls --filter "name=^${COMPOSE_PROJECT_NAME}-"  --format "{{.ID}}" | xargs docker container inspect --format '	{{.Name}}	{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}	{{range $p, $conf := .NetworkSettings.Ports}}{{$p}} {{end}}'; } 2>/dev/null || true
```
Comment (markkuriekkinen) [inline docker-up.sh:124]: Is it now guaranteed that the container names always use dashes (like `aplus-plus-1`) instead of underscores (`aplus_plus_1`)? Or could it still vary between platforms like Linux and Windows?

**Review by markkuriekkinen — APPROVED** [review]
Looks good! I have a question below.

File: docker-up.sh (hunk 1 above)
Comment (markkuriekkinen) [reply docker-up.sh:124]: After a quick experiment with the old and new Compose versions, I think that the old version uses underscores (`_`) in the container names and the new version uses hyphens (`-`). At least on my Linux, I witnessed such a difference.

```
# New
docker compose version
Docker Compose version v2.21.0

# Old
docker-compose --version
docker-compose version 1.29.2, build unknown
```

That's enough about the underscore. No need to spend more time on that.
